#!/usr/bin/env bash
# World wide web

if [ "$#" -eq 1 ]; then
    for subdomain in www lb-01 web-01 web-02; do
        result=$(dig $subdomain.$1 +short)
        if [ -n "$result" ]; then
            echo "The subdomain $subdomain is an A record and points to $result"
        else
            echo "The subdomain $subdomain does not exist for $1"
        fi
    done
elif [ "$#" -eq 2 ]; then
    subdomain=$2
    echo "$(dig $subdomain.$1 | awk '/ANSWER SECTION:/ {getline; print "The subdomain '"$subdomain"' is a "$4" record and points to "$5}')"
fi

