#!/usr/bin/env bash
# World wide web

if [ "$#" -eq 1 ]; then
    for subdomain in www lb-01 web-01 web-02; do
        result=$(dig $subdomain.$1 +short)
        if [ -n "$result" ]; then
            echo "The subdomain $subdomain is an A record and points to $result"
        else
            echo "The subdomain $subdomain does not exist for $1"
        fi
    done
elif [ "$#" -eq 2 ]; then
    domain=$1
    subdomain=$2
    result=$(dig $subdomain.$domain +short)
    if [ -n "$result" ]; then
        echo "The subdomain $subdomain is an A record and points to $result"
    else
        echo "The subdomain $subdomain does not exist for $domain"
    fi
else
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi
