#!/usr/bin/env bash
# install and config haproxy
sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver server1 35.175.135.83:80 check\n\tserver server2 100.26.158.195:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
