#!/usr/bin/env bash
#4 bad luck, 8 is your chance

i=1
while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    fi
    ((i++))
done