#!/usr/bin/env bash
#print 12h and 59min

hr=0
while [ $hr -le 12 ]
do
    echo "Hour: $hr"
    min=1
    while [ $min -le 59 ]
    do
        echo $min
        (( min++ ))
    done
    (( hr++ ))
done