#!/usr/bin/env bash
# Check if Nginx is running

if service nginx status > /dev/null; then
    sudo service nginx restart
else
    echo "Nginx is not running."
fi

echo "user nginx;" >> /etc/nginx/nginx.conf

chmod 644 /etc/nginx/nginx.conf

sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo service nginx restart
