#!/usr/bin/env bash
server {
    listen 80;
    server_name 35.175.135.83;

    location /api/ {
        proxy_pass http://127.0.0.1:5002;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Additional configuration if needed
}